### ISSUE TITLE
Might be possible to do web export

### ISSUE THREAD

**Issue by fire** [Fenreliania/OKHSL-Picker#2]
https://fenreliania.itch.io/okhsl-picker might benefit from a web export

**Comment by Fenreliania** [comment]
By web export, do you mean exporting as a web program so that the picker can be run in browser on itch?

**Comment by fire** [comment]
Yes!

**Comment by fire** [comment]
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html

**Comment by Fenreliania** [comment]
I'll give it a go in the next few days.

**Comment by Fenreliania** [comment]
Web version has been uploaded and confirmed functional.

**Comment by fire** [comment]
Thanks
